spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kayaan_db?useUnicode=true&characterEncoding=UTF-8&sslMode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

