spring:
  application:
    name: Kayaan-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/kayaan
    driver-class-name: org.postgresql.Driver
    username: kayaan
    password: secret
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  storage:
    endpoint: http://localhost:9002   # แก้ตรงนี้
    accessKey: minioadmin
    secretKey: minioadmin123
    bucket: kayaan-files
    region: ap-southeast-1
  security:
    jwt:
      enabled: false
      secretKey: dev-secret
      expirationMs: 86400000