spring:
  application:
    name: Kayaan-Backend
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Error handling configuration
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

# Logging configuration (base defaults; override per profile)
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY:${JWT_SECRET}}
      expiration: 86400000
      refresh-token:
        expiration: 604800000

kayaan:
  supabase:
    url: ${SUPABASE_URL}
    service-key: ${SUPABASE_SERVICE_KEY}
    buckets:
      avatars: ${SUPABASE_BUCKET_AVATARS:avatars}
      ai: ${SUPABASE_BUCKET_AI:ai-outputs}
      library: ${SUPABASE_BUCKET_STUDY_CONTENT:${SUPABASE_BUCKET_LIBRARY:study-content}}
    realtime:
      enabled: false
      groupChannelPrefix: groups.
    signed-get-ttl: ${SIGNED_GET_TTL:300}
    signed-get-skew-sec: ${SIGNED_GET_SKEW_SEC:10}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

avatar:
  upload-dir: ${user.dir}/uploads/avatars