CREATE TABLE IF NOT EXISTS group_invite (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    group_id INT NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked BOOLEAN DEFAULT FALSE NOT NULL,
    FOREIGN KEY (group_id) REFERENCES study_group(groupid) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES _user(id) ON DELETE CASCADE
);
